version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ecgscanner
      POSTGRES_USER: ecguser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecguser -d ecgscanner"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ECG Scanner Backend
  backend:
    build: ./backend
    expose:
      - "5001"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://ecguser:${DB_PASSWORD:-securepassword123}@postgres:5432/ecgscanner
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@ecgscanner.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - CORS_ORIGINS=https://*,http://*
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Nginx with SSL
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
